# Configuation file to get and generate all data required for the recombinant analysis notebook.

# Name of the directory to put data and results in NOTE: Do not change!
DATA_DIR: "data"

# Date of the MAT used for analysis
MAT_DATE: "2023-12-25"
# Name of the MAT and metadata file used in this analysis
MAT: gisaidAndPublic.2023-12-25.masked.nextclade.pangolin.pb
METADATA: gisaidAndPublic.2023-12-25.metadata.tsv

# RIVET results files copied into DATA_DIR directory
RIVET_RESULTS_FILE: "final_recombinants_2023-12-25.txt"
RIVET_VCF_FILE: "trios.vcf"

# Decide which steps to rerun
RERUN_CHRONUMENTAL: True
RERUN_GENETIC_DIVERSITY: False  # Or provide a single month, ie) "2020-07" 

# Names of data files in the 'DATA_DIR' directory
RECOMBINATION_STATS_FILE: "rivet_recombs_data.csv"
CHRONUMENTAL_FILE: "chronumental_dates_gisaidAndPublic.2023-12-25-STEPS2000-SERIAL3.metadata.tsv.tsv"
PYRO_MUTATIONS_FILE: "mutations.tsv"
CASES_FILE: "time_series_covid19_confirmed_global.csv"
GENETIC_DIVERSITY_FILE: "genetic-diversity-gisaidAndPublic.2023-12-25.csv"
MONTHLY_FITNESS_STATS: "monthly_fitness_stats.csv"
SUBTITUTION_SCORES: "substitutions_scores.csv"
